apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
      role: app
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
      role: db

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
  selector:
      role: redis
